# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eae7a683d1a9c1fcae4c9a6c1c6e5358e16ec2143b649a7e279090837ea928bc738f86134715cea6621f15926fcfdc551b403f09e86aaec88f7c76b526f442c

test:
  secret_key_base: c08413de95226d773eb8aa4bb5ccb30f6e64123fa6c74e34f499a3be513c68ea95657599c62f361170394dfe3704bddee32e6a7588333c0cfb080a57ed836a87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
